#!/usr/bin/perl -w
use Cow;
use Horse;
use Sheep;
use Mouse;
use strict;

my @arr = qw(Cow Cow Horse Horse Sheep Mouse);


print Horse->name,"\n";
my $tv_horse = Horse->named('Mr.Ed');
print "$tv_horse->name\n";

#Cow->speak;
# Cow->speak;
# Horse->speak;
# Sheep->speak;
 #foreach my $xx (@arr){
 #    $xx->speak;
 ##     print "$xx\n";
 #}
#Cow::speak;
#Horse::speak;
#Sheep::speak;



